version: '3.7'
services:
    telegram:
        build: ./TelegramManager/
        environment:
            POSTGRES_DB_HOST: database
            TELEGRAM_API_TOKEN: "$TELEGRAM_API_TOKEN"
            POSTGRES_USER: "$POSTGRES_USER"
            POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
            POSTGRES_DB: "$POSTGRES_DB"
        hostname: telegram
        restart: always
        links:
            - database
        volumes_from:
            - database
        depends_on:
            - database
    database:
        restart: always
        image: postgres:13.1
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_USER: "$POSTGRES_USER"
            POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
            POSTGRES_DB: "$POSTGRES_DB"
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
        - 5432:5432


volumes:
    db-data:

     



                    
